# Support Vector Regression

## No Follower

### Load Data

In [2]:
df = pd.read_csv('df_pos.csv', index_col=0)
df = df.drop('player_name', axis=1)

In [3]:
df_nf = df.drop('follower', axis=1)
df_nf

position        age      height     weight    rating  value  shots_total  \
0    2.000000  25.000000  184.000000  78.000000  2.333333   20.0       0.5540   
1    4.000000  27.000000  181.000000  72.000000  5.250000   32.0       2.8168   
2    3.000000  24.000000  188.000000  78.000000  6.000000   24.0       0.3802   
3    4.000000  25.000000  171.000000  70.000000  7.000000   32.0       1.9736   
4    2.000000  32.000000  180.000000  75.000000  4.833333   32.0       3.0823   
..        ...        ...         ...        ...       ...    ...          ...   
366  4.000000  28.000000  180.000000  66.000000  3.888889   44.0       2.0280   
367  3.769231  23.076923  188.230769  86.769231  1.615385   24.0       0.4836   
368  4.000000  32.000000  175.000000  77.000000  6.153846   22.5       2.5586   
369  4.000000  26.000000  192.000000  84.000000  6.545455   24.0       2.0141   
370  2.000000  23.000000  176.000000  72.000000  4.384615   44.0       1.6977   

     shots_on  goals_total  goals_conceded  ...  penalty_commited  \
0      0.1288       0.0129             0.0  ...            0.0000   
1      1.0538       0.4432             0.0  ...            0.0000   
2      0.0613       0.0000             0.0  ...            0.0000   
3      0.8442       0.2282             0.0  ...            0.0114   
4      1.1138       0.4705             0.0  ...            0.0192   
..        ...          ...             ...  ...               ...   
366    0.7120       0.2373             0.0  ...            0.0000   
367    0.2579       0.3761             0.0  ...            0.0000   
368    0.9795       0.2798             0.0  ...            0.0000   
369    0.7524       0.3357             0.0  ...            0.0000   
370    0.6011       0.1476             0.0  ...            0.0000   

     penalty_success  penalty_missed  penalty_saved  games_appearences  \
0             0.0000          0.0000            0.0             1.4044   
1             0.0985          0.0295            0.0             1.0538   
2             0.0000          0.0000            0.0             1.1160   
3             0.0000          0.0000            0.0             1.5515   
4             0.0096          0.0096            0.0             1.2003   
..               ...             ...            ...                ...   
366           0.0000          0.0000            0.0             1.0248   
367           0.0000          0.0107            0.0             1.2143   
368           0.0500          0.0000            0.0             1.4592   
369           0.0116          0.0000            0.0             1.4006   
370           0.0105          0.0000            0.0             1.2021   

     games_lineups  substitutes_in  substitutes_out  substitutes_bench  \
0           0.9277          0.4767           0.2577             0.5927   
1           0.9947          0.0591           0.0689             0.0689   
2           1.0056          0.1104           0.1839             0.7603   
3           0.9697          0.5818           0.6731             0.6160   
4           1.0754          0.1248           0.5857             0.2401   
..             ...             ...              ...                ...   
366         0.9924          0.0324           0.0647             0.0324   
367         1.0531          0.1612           0.5158             0.3116   
368         1.0294          0.4298           0.5397             0.5197   
369         0.9492          0.4514           0.2894             0.5788   
370         1.0334          0.1687           0.3058             0.2636   

     games_played  
0         77.6111  
1        101.5333  
2         81.5444  
3         87.6556  
4        104.1444  
..            ...  
366       92.7000  
367       93.0556  
368      100.0556  
369       86.3889  
370       94.8333  

[371 rows x 37 columns]

In [10]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

z = 10
scores_rm = np.zeros([2, z])

cv = KFold(z, shuffle=True, random_state=0)
for i, (idx_train, idx_test) in enumerate(cv.split(df_nf)):
    df_train = df_nf.iloc[idx_train]
    df_test = df_nf.iloc[idx_test]
    
    X_train = df_train.drop('value', axis=1).astype(float)
    X_train = StandardScaler().fit_transform(X_train)
    y_train = df_train['value']
    
    model = SVR(kernel="rbf", C=25)
    result = model.fit(X_train, y_train)
    
    
    pred = result.predict(StandardScaler().fit_transform(df_test.drop('value', axis=1)))
    rsquared = r2_score(df_test.value, pred)
    mse = mean_squared_error(df_test.value, pred)
    
    scores_rm[0, i] = model.score(X_train, y_train)
    scores_rm[1, i] = mse
    
    print("R2 = {:.8f}".format(model.score(X_train, y_train)))
    print("mse = {:.8f}".format(mse))
    
print("모델 성능 : R2 = {}, mse = {}".format(scores_rm[0].mean(), scores_rm[1].mean()))

R2 = 0.59137306
mse = 371.25935769
R2 = 0.59530017
mse = 463.05545510
R2 = 0.56799231
mse = 409.57090672
R2 = 0.58138376
mse = 162.94208254
R2 = 0.60219407
mse = 175.40204102
R2 = 0.58190285
mse = 766.17847639
R2 = 0.58011303
mse = 265.40491132
R2 = 0.56866046
mse = 491.36650242
R2 = 0.59216278
mse = 294.01917969
R2 = 0.56954006
mse = 200.08897565
모델 성능 : R2 = 0.5830622538016306, mse = 359.9287888551415


In [11]:
scores_rm

array([[5.91373056e-01, 5.95300172e-01, 5.67992308e-01, 5.81383763e-01,
        6.02194075e-01, 5.81902846e-01, 5.80113030e-01, 5.68660456e-01,
        5.92162778e-01, 5.69540056e-01],
       [3.71259358e+02, 4.63055455e+02, 4.09570907e+02, 1.62942083e+02,
        1.75402041e+02, 7.66178476e+02, 2.65404911e+02, 4.91366502e+02,
        2.94019180e+02, 2.00088976e+02]])

### Polynomial

In [19]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

z = 10
scores_rm = np.zeros([2, z])

cv = KFold(z, shuffle=True, random_state=0)
for i, (idx_train, idx_test) in enumerate(cv.split(df_nf)):
    df_train = df_nf.iloc[idx_train]
    df_test = df_nf.iloc[idx_test]
    
    X_train = df_train.drop('value', axis=1).astype(float)
    X_train = StandardScaler().fit_transform(X_train)
    y_train = df_train['value']
    
    model = SVR(kernel="poly", C=12)
    result = model.fit(X_train, y_train)
    
    
    pred = result.predict(StandardScaler().fit_transform(df_test.drop('value', axis=1)))
    rsquared = r2_score(df_test.value, pred)
    mse = mean_squared_error(df_test.value, pred)
    
    scores_rm[0, i] = model.score(X_train, y_train)
    scores_rm[1, i] = mse
    
    print("R2 = {:.8f}".format(model.score(X_train, y_train)))
    print("mse = {:.8f}".format(mse))
    
print("모델 성능 : R2 = {}, mse = {}".format(scores_rm[0].mean(), scores_rm[1].mean()))

R2 = 0.49290395
mse = 558.61802066
R2 = 0.44573830
mse = 388.34302649
R2 = 0.44985741
mse = 505.17633428
R2 = 0.44266709
mse = 193.92473994
R2 = 0.45817557
mse = 195.61597900
R2 = 0.39743210
mse = 824.50277956
R2 = 0.42730039
mse = 234.25493813
R2 = 0.45488520
mse = 659.66351289
R2 = 0.44028795
mse = 250.78507632
R2 = 0.45040073
mse = 260.26293552
모델 성능 : R2 = 0.44596486900959115, mse = 407.11473427835153


In [20]:
scores_rm

array([[4.92903953e-01, 4.45738297e-01, 4.49857406e-01, 4.42667095e-01,
        4.58175574e-01, 3.97432096e-01, 4.27300393e-01, 4.54885200e-01,
        4.40287947e-01, 4.50400728e-01],
       [5.58618021e+02, 3.88343026e+02, 5.05176334e+02, 1.93924740e+02,
        1.95615979e+02, 8.24502780e+02, 2.34254938e+02, 6.59663513e+02,
        2.50785076e+02, 2.60262936e+02]])

---

## Follower

### Data Pre-processing

In [6]:
from sklearn.preprocessing import StandardScaler

X = df.drop('value', axis=1).astype(float)
X = StandardScaler().fit_transform(X)
y = df['value']
y = np.array(y).reshape(-1, 1)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

### Train Model

In [75]:
regressor = SVR(kernel='rbf')
result = regressor.fit(X,y)
y_pred = result.predict(X_test)

C:\Users\Gk\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Model Selection

In [76]:
from sklearn.metrics import r2_score, mean_squared_error
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mse)
r2, mse, rmse

(-0.02846075041973406, 511.3942167760575, 22.614026991583287)

In [14]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

z = 10
scores_rm = np.zeros([2, z])

cv = KFold(z, shuffle=True, random_state=0)
for i, (idx_train, idx_test) in enumerate(cv.split(df)):
    df_train = df.iloc[idx_train]
    df_test = df.iloc[idx_test]
    
    X_train = df_train.drop('value', axis=1).astype(float)
    X_train = StandardScaler().fit_transform(X_train)
    y_train = df_train['value']
    
    model = SVR(kernel="rbf", C=25)
    result = model.fit(X_train, y_train)
    
    
    pred = result.predict(StandardScaler().fit_transform(df_test.drop('value', axis=1)))
    rsquared = r2_score(df_test.value, pred)
    mse = mean_squared_error(df_test.value, pred)
    
    scores_rm[0, i] = model.score(X_train, y_train)
    scores_rm[1, i] = mse
    
    print("R2 = {:.8f}".format(model.score(X_train, y_train)))
    print("mse = {:.8f}".format(mse))
    
print("모델 성능 : R2 = {}, mse = {}".format(scores_rm[0].mean(), scores_rm[1].mean()))

R2 = 0.61155552
mse = 353.04313977
R2 = 0.61711860
mse = 444.21546809
R2 = 0.58188113
mse = 371.51032773
R2 = 0.60366968
mse = 160.04525965
R2 = 0.62275761
mse = 194.70037148
R2 = 0.60251120
mse = 726.83893222
R2 = 0.59621895
mse = 250.16835829
R2 = 0.59449161
mse = 454.73825203
R2 = 0.61481785
mse = 282.68364581
R2 = 0.59203962
mse = 170.74225144
모델 성능 : R2 = 0.6037061757259524, mse = 340.8686006527236


In [15]:
scores_rm

array([[6.11555518e-01, 6.17118603e-01, 5.81881126e-01, 6.03669678e-01,
        6.22757606e-01, 6.02511199e-01, 5.96218952e-01, 5.94491605e-01,
        6.14817847e-01, 5.92039622e-01],
       [3.53043140e+02, 4.44215468e+02, 3.71510328e+02, 1.60045260e+02,
        1.94700371e+02, 7.26838932e+02, 2.50168358e+02, 4.54738252e+02,
        2.82683646e+02, 1.70742251e+02]])

In [25]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

z = 10
scores_rm = np.zeros([2, z])

cv = KFold(z, shuffle=True, random_state=0)
for i, (idx_train, idx_test) in enumerate(cv.split(df)):
    df_train = df.iloc[idx_train]
    df_test = df.iloc[idx_test]
    
    X_train = df_train.drop('value', axis=1).astype(float)
    X_train = StandardScaler().fit_transform(X_train)
    y_train = df_train['value']
    
    model = SVR(kernel="poly", C=12)
    result = model.fit(X_train, y_train)
    
    
    pred = result.predict(StandardScaler().fit_transform(df_test.drop('value', axis=1)))
    rsquared = r2_score(df_test.value, pred)
    mse = mean_squared_error(df_test.value, pred)
    
    scores_rm[0, i] = model.score(X_train, y_train)
    scores_rm[1, i] = mse
    
    print("R2 = {:.8f}".format(model.score(X_train, y_test)))
    print("mse = {:.8f}".format(mse))
    
print("모델 성능 : R2 = {}, mse = {}".format(scores_rm[0].mean(), scores_rm[1].mean()))

R2 = 0.50055872
mse = 550.56034369
R2 = 0.49284651
mse = 353.43990708
R2 = 0.45636087
mse = 506.61637975
R2 = 0.44950678
mse = 216.58020487
R2 = 0.46542506
mse = 215.89334686
R2 = 0.39987795
mse = 846.23989120
R2 = 0.42991427
mse = 226.86704024
R2 = 0.46637338
mse = 659.13140182
R2 = 0.44780245
mse = 238.79094560
R2 = 0.45711765
mse = 246.31353799
모델 성능 : R2 = 0.45657836356611725, mse = 406.04329991012554


In [26]:
scores_rm

array([[5.00558718e-01, 4.92846510e-01, 4.56360871e-01, 4.49506776e-01,
        4.65425064e-01, 3.99877952e-01, 4.29914274e-01, 4.66373376e-01,
        4.47802449e-01, 4.57117646e-01],
       [5.50560344e+02, 3.53439907e+02, 5.06616380e+02, 2.16580205e+02,
        2.15893347e+02, 8.46239891e+02, 2.26867040e+02, 6.59131402e+02,
        2.38790946e+02, 2.46313538e+02]])